# Generated by Django 3.0.3 on 2020-07-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=16)),
                ('inp_comment', models.CharField(max_length=160)),
                ('result', models.CharField(max_length=8)),
            ],
        ),
    ]
